"""Add missing user columns

Revision ID: f4474d6e8b85
Revises: 001_initial
Create Date: 2026-01-06 17:33:48.123627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4474d6e8b85'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context_sessions', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('context_sessions', sa.Column('client_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('context_sessions', sa.Column('context_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('context_sessions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('context_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_context_sessions_session_id'), table_name='context_sessions')
    op.create_index(op.f('ix_context_sessions_session_id'), 'context_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_context_sessions_id'), 'context_sessions', ['id'], unique=False)
    op.drop_column('context_sessions', 'is_active')
    op.drop_column('context_sessions', 'metadata')
    op.add_column('context_versions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('context_versions', 'change_reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_context_versions_version'), table_name='context_versions')
    op.create_index(op.f('ix_context_versions_id'), 'context_versions', ['id'], unique=False)
    op.create_index('ix_version_context_version', 'context_versions', ['context_id', 'version'], unique=False)
    op.add_column('contexts', sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contexts', sa.Column('session_id', sa.String(length=100), nullable=True))
    op.alter_column('contexts', 'context_type',
               existing_type=postgresql.ENUM('temporal', 'spatial', 'situational', 'meta', name='context_type'),
               type_=sa.Enum('TEMPORAL', 'SPATIAL', 'SITUATIONAL', 'META', name='contexttype'),
               existing_nullable=False)
    op.alter_column('contexts', 'memory_tier',
               existing_type=postgresql.ENUM('long_term', 'short_term', 'ephemeral', name='memory_tier'),
               type_=sa.Enum('LONG_TERM', 'SHORT_TERM', 'EPHEMERAL', name='memorytier'),
               existing_nullable=False,
               existing_server_default=sa.text("'short_term'::memory_tier"))
    op.alter_column('contexts', 'drift_status',
               existing_type=postgresql.ENUM('stable', 'drifting', 'conflicting', 'stale', name='drift_status'),
               type_=sa.Enum('STABLE', 'DRIFTING', 'CONFLICTING', 'STALE', name='driftstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'stable'::drift_status"))
    op.drop_index(op.f('ix_contexts_user_type_key'), table_name='contexts')
    op.create_index('ix_context_expires', 'contexts', ['expires_at'], unique=False, postgresql_where='expires_at IS NOT NULL')
    op.create_index('ix_context_user_active', 'contexts', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_context_user_type_key', 'contexts', ['user_id', 'context_type', 'key'], unique=False)
    op.create_index(op.f('ix_contexts_expires_at'), 'contexts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_contexts_id'), 'contexts', ['id'], unique=False)
    op.create_index(op.f('ix_contexts_session_id'), 'contexts', ['session_id'], unique=False)
    op.drop_column('contexts', 'last_accessed_at')
    op.drop_column('contexts', 'is_deleted')
    op.drop_column('contexts', 'access_count')
    op.drop_column('contexts', 'last_verified_at')
    op.alter_column('tenants', 'api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('tenants', 'api_key_secondary',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_constraint(op.f('tenants_api_key_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('tenants_slug_key'), 'tenants', type_='unique')
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=True)
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.drop_column('tenants', 'is_deleted')
    op.drop_column('tenants', 'rate_limits')
    op.add_column('users', sa.Column('default_country', sa.String(length=3), nullable=True))
    op.add_column('users', sa.Column('allow_location_tracking', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('allow_situational_tracking', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'allow_situational_tracking')
    op.drop_column('users', 'allow_location_tracking')
    op.drop_column('users', 'default_country')
    op.add_column('tenants', sa.Column('rate_limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=False)
    op.drop_index(op.f('ix_tenants_api_key'), table_name='tenants')
    op.create_index(op.f('ix_tenants_api_key'), 'tenants', ['api_key'], unique=False)
    op.create_unique_constraint(op.f('tenants_slug_key'), 'tenants', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_api_key_key'), 'tenants', ['api_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'api_key_secondary',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('tenants', 'api_key',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('contexts', sa.Column('last_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('contexts', sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('contexts', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('contexts', sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contexts_session_id'), table_name='contexts')
    op.drop_index(op.f('ix_contexts_id'), table_name='contexts')
    op.drop_index(op.f('ix_contexts_expires_at'), table_name='contexts')
    op.drop_index('ix_context_user_type_key', table_name='contexts')
    op.drop_index('ix_context_user_active', table_name='contexts')
    op.drop_index('ix_context_expires', table_name='contexts', postgresql_where='expires_at IS NOT NULL')
    op.create_index(op.f('ix_contexts_user_type_key'), 'contexts', ['user_id', 'context_type', 'key'], unique=False)
    op.alter_column('contexts', 'drift_status',
               existing_type=sa.Enum('STABLE', 'DRIFTING', 'CONFLICTING', 'STALE', name='driftstatus'),
               type_=postgresql.ENUM('stable', 'drifting', 'conflicting', 'stale', name='drift_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'stable'::drift_status"))
    op.alter_column('contexts', 'memory_tier',
               existing_type=sa.Enum('LONG_TERM', 'SHORT_TERM', 'EPHEMERAL', name='memorytier'),
               type_=postgresql.ENUM('long_term', 'short_term', 'ephemeral', name='memory_tier'),
               existing_nullable=False,
               existing_server_default=sa.text("'short_term'::memory_tier"))
    op.alter_column('contexts', 'context_type',
               existing_type=sa.Enum('TEMPORAL', 'SPATIAL', 'SITUATIONAL', 'META', name='contexttype'),
               type_=postgresql.ENUM('temporal', 'spatial', 'situational', 'meta', name='context_type'),
               existing_nullable=False)
    op.drop_column('contexts', 'session_id')
    op.drop_column('contexts', 'last_confirmed_at')
    op.drop_index('ix_version_context_version', table_name='context_versions')
    op.drop_index(op.f('ix_context_versions_id'), table_name='context_versions')
    op.create_index(op.f('ix_context_versions_version'), 'context_versions', ['version'], unique=False)
    op.alter_column('context_versions', 'change_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('context_versions', 'updated_at')
    op.add_column('context_sessions', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('context_sessions', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_context_sessions_id'), table_name='context_sessions')
    op.drop_index(op.f('ix_context_sessions_session_id'), table_name='context_sessions')
    op.create_index(op.f('ix_context_sessions_session_id'), 'context_sessions', ['session_id'], unique=False)
    op.alter_column('context_sessions', 'session_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('context_sessions', 'updated_at')
    op.drop_column('context_sessions', 'context_snapshot')
    op.drop_column('context_sessions', 'client_info')
    op.drop_column('context_sessions', 'last_activity_at')
    # ### end Alembic commands ###
